name: "multi event pipeline"

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
      - test

jobs:
  show-message:
    runs-on: ubuntu-latest

    steps:
      - name: "Print branch info"
        run: echo "This job ran on a push or pull request to master or test branch"
